### ISSUE TITLE
Add alert feature for deregistered nodes

### ISSUE THREAD

**Issue by tokerato** [jagerman/loki-sn-bot#1]
Please add an alert feature for nodes nearing expiry (48 hrs / 24 hrs).

Also adding feature to list deregistered nodes from main menu.

Thanks

**Comment by jagerman** [comment]
I forgot to comment on this: the alert for nodes nearing expiry has been in place for a couple weeks now (since 55d034206aca5b1867e56822f9d679304ee8dd94).

I've also just now pushed a change (6b68be590566a23b2c6c39b031c2a40f70c5fc69) for make it easy to tell SN status from the SN menu by adding a status icon to it:


![image](https://user-images.githubusercontent.com/4459524/49674991-23350000-fa4a-11e8-9afe-a66cdf744804.png)
